### ISSUE TITLE
Run over the "Check initial coordinates" with a For Loop? 

### ISSUE THREAD

**Issue by hherde** [sciollalab/BNL_ThermomechanicalStave#24]
Can we clean up the code by running a For Loop around the Check Initial Coordinates scheme? That way, we do not need three while loops performing essentially identical functions.

**Comment by sciollalab** [comment]
Yes! Turns out this is the way to do this piece of code. Jogging was freezing the program because we wanted to jog three times (once each for the different calibration coordinates), but each jog instance requires an event structure. LabVIEW can only process one event structure per block diagram! So we _have to_ put the event structure inside of the For Loop.

Issue resolved in commit f66513aca89ec8193d953915cea709277ea140ad: "Post Test Result: Successful!" on 21 April 2017
